apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-service
  namespace: euniceb-org
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/window: "60s"
    spec:
      containers:
        - image: dashaun/org.euniceb.service.gateway:v0.0.1
          env:
          - name: ZIPKIN_ENDPOINT
            value: http://openzipkin.euniceb-org.svc.cluster.local:9411/api/v2/spans 
